### ISSUE TITLE
Add a sync button to force device time

### ISSUE THREAD

**Issue by ldmpub** [ldmpub/ACaWA-issues#22]
**Suggestion details**: being able to set device time with current NTP time.

**Remarks**:

- additional permission may be required (depends on Android version?) but it seems possible without root access
- if possible, please prompt user for the new permission only on sync time action (not during install / first app launch)
- Look at existing apps doing this (some may even be open source?): https://play.google.com/store/apps/details?id=ru.org.amip.ClockSync

**Comment by thubalek** [comment]
Unfortunately this is possible only on old versions of Androids/rooted device so I'm not going to invest to this feature. Sorry.

**Comment by ldmpub** [comment]
Thanks for your explanations => rejected for technical reasons.
