### ISSUE TITLE
Share options are not "material design"

### ISSUE THREAD

**Issue by ldmpub** [ldmpub/ACaWA-issues#3]
The current share dialog looks like (except the bullets that have already been fixed):
![strange ui for a choice](https://user-images.githubusercontent.com/1452146/42909758-77667156-8ae5-11e8-9cfc-a599431f04b1.png)
=> user should click on the text to indicate his choice (it's not obvious).

**Suggestion**
use a layout with "radio buttons" in front of each line / choice, screen already available in the app:
![radio buttons](https://user-images.githubusercontent.com/1452146/42909822-ab1f9d92-8ae5-11e8-8a25-905bd94c651d.png)
Note: screenshot from the Preferences>Theme Dialog of the ACaWA app.

**Comment by thubalek** [comment]
Fixed

**Comment by ldmpub** [comment]
Current layout for this dialog in beta version of the app is text only.
From my point of view: simple text do not indicate clearly to user he should perform a choice, radio buttons, like shown above, are more appropriate.

As far as this is minor (because both exports are working) => I close this issue.

Thanks.
